### ISSUE TITLE
Installing ActiveSilicon driver

### ISSUE THREAD

**Issue by samkleeman1** [chaichontat/goff-rotation#2]
Hi,

Thanks so much for making this available. We are currently trying to get setup on Windows 10. We have been having difficulty installing the Illumina Active Silicon driver, seeing error messages along the lines of: 'Wrong current folder, installer aborter'.

Do you have any advice?

Many thanks,

Sam Kleeman
PhD Student, Cold Spring Harbor Laboratory, NY

**Comment by chaichontat** [comment]
Hi! I also encountered the same error. The trick is to install the driver directly using Device Manager (similar to this [video](https://www.youtube.com/watch?v=u3cRtGxEav4)) using the driver folder.

<img width="817" alt="image" src="https://user-images.githubusercontent.com/34997334/149604963-3670b093-c484-4c04-a0e3-8bb0f5ff1871.png">

If you still have issues, please share the screenshot of your Device Manager.
